# Generated by Django 6.0 on 2025-12-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('current_stage', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('MARKETING', 'Marketing'), ('MOCK_EXAM', 'Mock Exam'), ('GENERAL_BOT', 'General Bot')], default='ONBOARDING', max_length=50)),
                ('exam_question_counter', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, null=True)),
                ('last_admin_reply_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_interaction_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
