# Generated by Django 6.0 on 2025-12-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CRIMINAL_LAW', 'Criminal Law'), ('CIVIL_LAW', 'Civil Law'), ('REMEDIAL_LAW', 'Remedial Law'), ('POLITICAL_LAW', 'Political Law'), ('LABOR_LAW', 'Labor Law'), ('TAX_LAW', 'Tax Law'), ('COMMERCIAL_LAW', 'Commercial Law'), ('ETHICS', 'Legal Ethics')], max_length=50)),
                ('question_text', models.TextField()),
                ('expected_answer', models.TextField()),
                ('rubric_criteria', models.TextField()),
            ],
        ),
    ]
