# Generated by Django 6.0 on 2025-12-17 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_question_id_asked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.question'),
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('grammar_feedback', models.TextField(blank=True, null=True)),
                ('legal_basis_feedback', models.TextField(blank=True, null=True)),
                ('application_feedback', models.TextField(blank=True, null=True)),
                ('conclusion_feedback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.user')),
            ],
        ),
    ]
