# Generated by Django 6.0 on 2025-12-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_user_last_question_id_asked_examresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rubric_criteria',
        ),
    ]
