# Generated by Django 6.0 on 2025-12-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
