# Generated by Django 6.0 on 2025-12-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_user_academic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_sub_stage',
            field=models.CharField(blank=True, choices=[('ASK_NAME', 'Ask Name'), ('ASK_ACADEMIC_STATUS', 'Ask Academic Status')], max_length=50, null=True),
        ),
    ]
