# Generated by Django 6.0 on 2025-12-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_user_onboarding_sub_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_registered_website_user',
            field=models.BooleanField(default=False),
        ),
    ]
