# Generated by Django 6.0 on 2025-12-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_user_is_registered_website_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_re_engagement_stage_sent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
