# Generated by Django 6.0 on 2025-12-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_user_last_re_engagement_stage_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_re_engagement_stage_sent',
            new_name='re_engagement_stage_index',
        ),
        migrations.AddField(
            model_name='user',
            name='last_re_engagement_message_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
