# Generated by Django 6.0 on 2025-12-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_rename_last_re_engagement_stage_sent_user_re_engagement_stage_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='grammar_feedback',
            new_name='legal_writing_feedback',
        ),
    ]
