# Generated by Django 6.0 on 2025-12-20 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_grammar_feedback_examresult_legal_writing_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_admin_reply_timestamp',
        ),
    ]
