# Generated by Django 6.0 on 2025-12-20 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_user_last_admin_reply_timestamp'),
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course this question belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal.course'),
        ),
    ]
