# Generated by Django 6.0 on 2025-12-20 14:57

from django.db import migrations, models
import inspect # For extracting constants from prompts.py
import chat.prompts # Import the module containing the prompt constants


def populate_prompts(apps, schema_editor):
    Prompt = apps.get_model('chat', 'Prompt')

    # Helper to get all uppercase variables from chat.prompts
    # prompt_constants = inspect.getmembers(chat.prompts, lambda x: inspect.ismodule(x) is False and x.__class__ is str and x.isupper())

    # Map categories to constants
    categorized_prompts = {
        'QUICK_REPLY': [
            'QUICK_REPLY_SYSTEM_PROMPT',
            'QUICK_REPLY_USER_PROMPT_TEMPLATE',
        ],
        'SUMMARIZATION': [
            'SUMMARIZE_SYSTEM_PROMPT',
            'SUMMARIZE_USER_PROMPT_WITH_EXISTING_SUMMARY_TEMPLATE',
            'SUMMARIZE_USER_PROMPT_WITHOUT_EXISTING_SUMMARY_TEMPLATE',
        ],
        'EXAM_GRADING': [
            'GRADE_EXAM_SYSTEM_PROMPT',
            'GRADE_EXAM_USER_PROMPT_TEMPLATE',
        ],
        'RE_ENGAGEMENT': [
            'RE_ENGAGEMENT_SYSTEM_PROMPT',
            'RE_ENGAGEMENT_USER_PROMPT_TEMPLATE',
        ],
        'ASSESSMENT': [
            'ASSESSMENT_SYSTEM_PROMPT',
            'ASSESSMENT_USER_PROMPT_TEMPLATE',
        ],
        'NAME_EXTRACTION': [
            'NAME_EXTRACTION_SYSTEM_PROMPT',
            'NAME_EXTRACTION_USER_PROMPT_TEMPLATE',
        ],
    }

    for category, names in categorized_prompts.items():
        for name in names:
            text_content = getattr(chat.prompts, name, None)
            if text_content:
                Prompt.objects.create(name=name, category=category, text_content=text_content)
            else:
                print(f"Warning: Prompt constant '{name}' not found in chat.prompts")

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_question_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for the prompt (e.g., QUICK_REPLY_SYSTEM_PROMPT)', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('QUICK_REPLY', 'Quick Reply'), ('SUMMARIZATION', 'Summarization'), ('EXAM_GRADING', 'Exam Grading'), ('RE_ENGAGEMENT', 'Re-engagement'), ('ASSESSMENT', 'User Strength Assessment'), ('NAME_EXTRACTION', 'Name Extraction')], help_text='Category of the prompt (e.g., QUICK_REPLY)', max_length=50)),
                ('text_content', models.TextField(help_text='The actual content of the prompt, potentially with placeholders')),
                ('description', models.TextField(blank=True, help_text="Optional description of the prompt's purpose", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Prompt',
                'verbose_name_plural': 'AI Prompts',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.RunPython(populate_prompts, migrations.RunPython.noop),
    ]
