# Generated by Django 6.0 on 2025-12-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_messenger_reachable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(help_text='Unique identifier for the prompt (e.g., QUICK_REPLY_SYSTEM_PROMPT). This should match the constant name in chat/prompts.py', max_length=255, unique=True),
        ),
    ]
