# Generated by Django 5.2 on 2025-12-23 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_chatlog_id_alter_examresult_id_alter_prompt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gpt_5_2_daily_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gpt_5_2_last_reset_date',
            field=models.DateField(default=datetime.date(2025, 12, 23)),
        ),
    ]
