# Generated by Django 5.2 on 2025-12-23 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_user_gpt_5_2_daily_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gpt_5_2_last_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
